version: '3.8'

x-env: &x-env
  DJANGO_ENV: local
x-image: &image {{ cookiecutter.project_slug }}:dev
x-volumes: &volumes
  - ../config/settings.yaml:/home/app/config/settings.yaml:ro
  - ../pyproject.toml:/home/app/pyproject.toml:ro
  - ../config/fixtures:/home/app/fixtures:ro
  - ../src:/home/app/libs:ro
  - ../tests:/home/app/tests:ro
  # Docker-Compose settings
  - ./config/override.yaml:/home/app/config/override.yaml:ro
  - ./config/.secrets.yaml:/home/app/config/.secrets.yaml:ro

services:

  # 1.0 pre-commit
  pre-commit:
    image: *image
    volumes:
      - ../:/tmp/backend:ro
      - ../.pre-commit-config.yaml:/home/app/.pre-commit-config.yaml:ro
      - ../.secrets.baseline:/home/app/.secrets.baseline:ro
    environment: *x-env
    working_dir: /home/app
    command: >
      bash -c "mkdir -p /home/app/apps/backend/
      && cp -R /tmp/backend/* /home/app/apps/backend/
      && cp /tmp/backend/.pre-commit-config.yaml /home/app/apps/backend/
      && cp /tmp/backend/.secrets.baseline /home/app/apps/backend/
      && cd /home/app/apps/backend/
      && git init -b test_main .
      && git add .
      && pre-commit run --a"

  # 1.1 Test Checks
  check:
    image: *image
    volumes: *volumes
    environment: *x-env
    entrypoint: python manage.py
    command: check --fail-level WARNING

  # 1.2 Test Migrations
  migrations:
    depends_on:
      check:
        condition: service_completed_successfully
    image: *image
    volumes: *volumes
    environment: *x-env
    entrypoint: bash -c
    command: >
      python manage.py makemigrations --no-input --check
      || (echo '::error::Migrations are not up to date, please run 'makemigrations' locally and push the changes.'
          && exit 1)

  # 2.1 Test Application
  test: &test
    depends_on:
      migrations:
        condition: service_completed_successfully
    image: *image
    volumes: *volumes
    environment: *x-env
    working_dir: /home/app
    entrypoint: pytest
    command:
      - --cov=service
      - --cov-report=html:/home/app/.artifacts/coverage/html
      - --cov-report=lcov:/home/app/.artifacts/coverage/.coverage.info  # TODO: covfile for github see: https://github.com/marketplace/actions/code-coverage-report
      - ./tests/

  # 3 Aggregate Test Results
  test-aggregate:
    depends_on:
      pre-commit:
        condition: service_completed_successfully
      test:
        condition: service_completed_successfully
    image: *image
    command: exit 0
